tls:
  certificates:
    - certFile: /etc/traefik/certs/server.crt
      keyFile: /etc/traefik/certs/server.key

http:
  routers:
    api:
      rule: "HostRegexp(`.+`)"
      service: api
      entryPoints:
        - websecure
      tls: {}

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:8000"
