http:
  routers:
    api:
      rule: "HostRegexp(`{host:.+}`)"
      service: api
      entryPoints:
        - websecure
      tls: {}

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:8000"
