tls:
  certificates:
    - certFile: /etc/traefik/certs/server.crt
      keyFile: /etc/traefik/certs/server.key

http:
  routers:
    api:
      rule: "Host(`fthackthon.dev`) || Host(`165.227.118.186`)"
      service: api
      entryPoints:
        - websecure
      tls: {}

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:8000"
